apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-demo-workshop-1
spec:
  title: TAP Demo Workshop 1
  description: A demonstration of a Workshop
  vendor: VMWare
  difficulty: beginner
  duration: 15m
  url: https://github.com/x95castle1/lab-tap-sample
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/x95castle1/lab-tap-sample?ref=main
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: default
      console:
        enabled: false
      editor:
        enabled: false